spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://kgesns.cbkz9u3lll2z.ap-northeast-2.rds.amazonaws.com:5432/kgesns
  username: postgres
  password: 12341234
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  # longer than 256 bit
  secret-key: fast_campus.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000